#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Red Hat Inc.  All Rights Reserved.
#
# FS QA Test No. 766
#
# Test file_getattr/file_setattr syscalls
#
. ./common/preamble
_begin_fstest auto

# Import common functions.
# . ./common/filter

_wants_kernel_commit xxxxxxxxxxx \
	"fs: introduce file_getattr and file_setattr syscalls"

# Modify as appropriate.
_require_scratch
_require_test_program "af_unix"
_require_test_program "file_attr"
_require_symlinks
_require_mknod

_scratch_mkfs >>$seqres.full 2>&1
_scratch_mount

file_attr () {
	$here/src/file_attr $*
}

create_af_unix () {
	$here/src/af_unix $* || echo af_unix failed
}

projectdir=$SCRATCH_MNT/prj

# Create normal files and special files
mkdir $projectdir
mkfifo $projectdir/fifo
mknod $projectdir/chardev c 1 1
mknod $projectdir/blockdev b 1 1
create_af_unix $projectdir/socket
touch $projectdir/foo
ln -s $projectdir/foo $projectdir/symlink
touch $projectdir/bar
ln -s $projectdir/bar $projectdir/broken-symlink
rm -f $projectdir/bar

echo "Initial attributes state"
file_attr --get $projectdir
file_attr --get $projectdir ./fifo
file_attr --get $projectdir ./chardev
file_attr --get $projectdir ./blockdev
file_attr --get $projectdir ./socket
file_attr --get $projectdir ./foo
file_attr --get $projectdir ./symlink

echo "Set FS_XFLAG_NODUMP (d)"
file_attr --set --set-nodump $projectdir
file_attr --set --set-nodump $projectdir ./fifo
file_attr --set --set-nodump $projectdir ./chardev
file_attr --set --set-nodump $projectdir ./blockdev
file_attr --set --set-nodump $projectdir ./socket
file_attr --set --set-nodump $projectdir ./foo
file_attr --set --set-nodump $projectdir ./symlink

echo "Read attributes"
file_attr --get $projectdir
file_attr --get $projectdir ./fifo
file_attr --get $projectdir ./chardev
file_attr --get $projectdir ./blockdev
file_attr --get $projectdir ./socket
file_attr --get $projectdir ./foo
file_attr --get $projectdir ./symlink

echo "Set attribute on broken link with AT_SYMLINK_NOFOLLOW"
file_attr --set --set-nodump $projectdir ./broken-symlink
file_attr --get $projectdir ./broken-symlink

file_attr --set --no-follow --set-nodump $projectdir ./broken-symlink
file_attr --get --no-follow $projectdir ./broken-symlink

cd $SCRATCH_MNT
touch ./foo2
echo "Initial state of foo2"
file_attr --get --at-cwd ./foo2
echo "Set attribute relative to AT_FDCWD"
file_attr --set --at-cwd --set-nodump ./foo2
file_attr --get --at-cwd ./foo2

echo "Set attribute on AT_FDCWD"
mkdir ./bar
file_attr --get --at-cwd ./bar
cd ./bar
file_attr --set --at-cwd --set-nodump ""
file_attr --get --at-cwd .

# success, all done
status=0
exit
